FROM keymetrics/pm2:latest-alpine
WORKDIR /usr/src/app
ADD . /usr/src/app  
RUN npm config set registry https://registry.npm.taobao.org/ && \  
    npm i
# RUN npm i
EXPOSE 3000
# CMD ["pm2-runtime", "start", "--json", "process.json"]
CMD ["pm2-runtime", "start",  "process.yml"]

# 基础镜像
FROM hayd/ubuntu-deno:1.0.0
# 工作目录
WORKDIR /usr/src/app
USER deno

# COPY index.ts .
# RUN deno cache deps.ts
# ADD添加
ADD . note

RUN deno cache main.ts
# 暴露端口
EXPOSE 2000  
CMD ["--allow-net", "main.ts"]