FROM keymetrics/pm2:latest-alpine
WORKDIR /usr/src/app
ADD . /usr/src/app  
RUN npm config set registry https://registry.npm.taobao.org/ && \  
    npm i
# RUN npm i
EXPOSE 3000
# CMD ["pm2-runtime", "start", "--json", "process.json"]
CMD ["pm2-runtime", "start",  "process.yml"]


FROM hayd/ubuntu-deno:1.0.0
EXPOSE 2000  
WORKDIR /usr/src/app
USER deno

# COPY index.ts .
# RUN deno cache deps.ts

ADD . .

RUN deno cache main.ts

CMD ["--allow-net", "main.ts"]